version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    # or 
    environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      - ANTHROPIC_API_KEY
    
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    networks:
    - dokploy-network

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
    - dokploy-network
    labels:
    - "traefik.http.routers.screenshottocode-screenshot-to-code-wgxpyh-2-web.middlewares": "traefik-forward-auth@file",
    ports:
      - "5173:5173"
      
networks:
 dokploy-network:
   external: true
