version: '3.9'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    
    env_file:
      - .env
    
    # or 
    environment:
      #- BACKEND_PORT=7001   # if you change the port, make sure to also change the VITE_WS_BACKEND_URL at frontend/.env.local
      - ANTHROPIC_API_KEY
      - OPENAI_API_KEY
    
    ports:
      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"

    labels:
      - traefik.http.routers.screenshottocode-api.entrypoints=websecure
      - traefik.http.routers.screenshottocode-api.middlewares=traefik-forward-auth@file
      - traefik.http.routers.screenshottocode-api.priority=100
      - traefik.http.routers.screenshottocode-api.tls.certresolver=letsencrypt
      - traefik.http.services.screenshottocode-api.loadbalancer.server.port=7001
      - "traefik.http.routers.screenshottocode-api.rule=Host(`screenshot-to-code.apps-cluster.livecycle.xyz`) && (PathPrefix(`/api`) || PathPrefix(`/generate-code`))"
      
    networks:
    - dokploy-network

    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
    - dokploy-network
    environment:
    - VITE_HTTP_BACKEND_URL
    - VITE_WS_BACKEND_URL
    labels:
    - traefik.http.routers.screenshottocode-screenshot-to-code-wgxpyh-2-websecure.middlewares=traefik-forward-auth@file
    - traefik.http.routers.screenshottocode-screenshot-to-code-wgxpyh-2-websecure.priority=10
    ports:
      - "5173:5173"
      
networks:
 dokploy-network:
   external: true
